---
abstract: 'Sybase API modules'
author:
  - 'Michael Peppler (mpeppler@peppler.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.58, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: sybperl
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/mpeppler/sybperl/issues
  repository: https://github.com/mpeppler/sybperl.git
version: '2.19'
